import {StartClientInheritanceProcessCommandInterface} from './StartClientInheritanceProcessCommandInterface';
import {SucceedItemClientInheritanceProcessCommandInterface} from './SucceedItemClientInheritanceProcessCommandInterface';
import {FailItemClientInheritanceProcessCommandInterface} from './FailItemClientInheritanceProcessCommandInterface';
import {CompleteClientInheritanceProcessCommandInterface} from './CompleteClientInheritanceProcessCommandInterface';

export {
  StartClientInheritanceProcessCommandInterface,
  SucceedItemClientInheritanceProcessCommandInterface,
  FailItemClientInheritanceProcessCommandInterface,
  CompleteClientInheritanceProcessCommandInterface
};
