FROM staffshift-agency-client-management

RUN apk add bash

COPY ./generate_docs.sh ./

ARG PRIVATE_SSH_KEY

ARG BRANCH_NAME

ENV GIT_BRANCH=$BRANCH_NAME

RUN  echo -e $PRIVATE_SSH_KEY >> $HOME/.ssh/id_rsa && chmod o-rw $HOME/.ssh/id_rsa && chmod g-rw $HOME/.ssh/id_rsa && /bin/bash -e ./generate_docs.sh && rm $HOME/.ssh/id_rsa
