version: '3.3'
services:
  staffshift-agency-client-management:
    image: staffshift-agency-client-management
    container_name: staffshift-agency-client-management
    ports:
    - "3370:3370"
    command: 'sh -c "node ./wait4mongo && npm run test && npm run lint"'
    environment:
    - NODE_ENV=ci
    depends_on:
    - mountebank
    - database
  mountebank:
    container_name: mountebank
    hostname: mountebank
    image: mountebank
    ports:
    - "2525:2525"
    - "4000:4000"
  database:
    container_name: database
    hostname: database
    image: database
    ports:
    - "27017:27017"
    extra_hosts:
    - "database:127.0.0.1"