import {AgencyClientConsultantAssignedEventDataInterface} from './AgencyClientConsultantAssignedEventDataInterface';
import {AgencyClientConsultantUnassignedEventDataInterface} from './AgencyClientConsultantUnassignedEventDataInterface';
import {AgencyConsultantRoleDetailsUpdatedEventDataInterface} from './AgencyConsultantRoleDetailsUpdatedEventDataInterface';

export {
  AgencyClientConsultantAssignedEventDataInterface,
  AgencyClientConsultantUnassignedEventDataInterface,
  AgencyConsultantRoleDetailsUpdatedEventDataInterface
};
