import {BaseEventStoreDataInterface} from 'EventStoreDataTypes/BaseEventStoreDataInterface';

export interface ConsultantJobAssignProcessCompletedEventStoreDataInterface extends BaseEventStoreDataInterface {}
