import {BaseEventStoreDataInterface} from 'EventStoreDataTypes/BaseEventStoreDataInterface';

export interface ConsultantJobAssignProcessStartedEventStoreDataInterface extends BaseEventStoreDataInterface {}
