import {
  ApplyPaymentTermOrganisationJobCommandDataInterface,
  CompleteApplyPaymentTermInheritanceOrganisationJobCommandDataInterface,
  CompleteApplyPaymentTermOrganisationJobCommandDataInterface,
  InheritPaymentTermOrganisationJobCommandDataInterface
} from './CommandTypes';
export type OrganisationJobCommandDataType =
  | CompleteApplyPaymentTermInheritanceOrganisationJobCommandDataInterface
  | InheritPaymentTermOrganisationJobCommandDataInterface
  | ApplyPaymentTermOrganisationJobCommandDataInterface
  | CompleteApplyPaymentTermOrganisationJobCommandDataInterface;
