import {AddAgencyConsultantRoleCommandDataInterface} from './CommandDataTypes/AddAgencyConsultantRoleCommandDataInterface';
import {UpdateAgencyConsultantRoleCommandDataInterface} from './CommandDataTypes/UpdateAgencyConsultantRoleCommandDataInterface';
import {EnableAgencyConsultantRoleCommandDataInterface} from './CommandDataTypes/EnableAgencyConsultantRoleCommandDataInterface';
import {DisableAgencyConsultantRoleCommandDataInterface} from './CommandDataTypes/DisableAgencyConsultantRoleCommandDataInterface';

export type AgencyCommandDataType =
  | AddAgencyConsultantRoleCommandDataInterface
  | UpdateAgencyConsultantRoleCommandDataInterface
  | EnableAgencyConsultantRoleCommandDataInterface
  | DisableAgencyConsultantRoleCommandDataInterface;
