import {BaseEventStoreDataInterface} from 'EventTypes/BaseEventStoreDataInterface';

export interface ConsultantJobAssignProcessCompletedEventStoreDataInterface extends BaseEventStoreDataInterface {}
