export {StartConsultantJobAssignCommandDataInterface} from './StartConsultantJobAssignCommandDataInterface';
export {ProgressConsultantJobAssignCommandDataInterface} from './ProgressConsultantJobAssignCommandDataInterface';
export {FailItemConsultantJobAssignCommandDataInterface} from './FailItemConsultantJobAssignCommandDataInterface';
export {CompleteConsultantJobAssignCommandDataInterface} from './CompleteConsultantJobAssignCommandDataInterface';