export {StartConsultantJobAssignCommandDataInterface} from './StartConsultantJobAssignCommandDataInterface';
export {SucceedItemConsultantJobAssignCommandDataInterface} from './SucceedItemConsultantJobAssignCommandDataInterface';
export {FailItemConsultantJobAssignCommandDataInterface} from './FailItemConsultantJobAssignCommandDataInterface';
export {CompleteConsultantJobAssignCommandDataInterface} from './CompleteConsultantJobAssignCommandDataInterface';
