name: Event Documentation Generator
on: [push]
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Checkout the project
      - name: Checkout Project
        uses: actions/checkout@v2
      # Install node
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install typescript
        run: npm install -g typescript
      - name: Install ts-node
        run: npm install -g ts-node
      - name: Run generator script
        run: npm run dev-generate-event-docs
