name: Event Documentation Generator
on: [push]
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Checkout the project
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      # Install node
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: NPM Install
        run: npm install
      - name: Run generator script
        run: npm run dev-generate-event-docs
