name: Event Documentation Generator
on: [push]
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Checkout the project
      - name: Checkout Project
        uses: actions/checkout@v2
      # Install ssh key
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      # Install node
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: NPM Install
        run: npm install
      - name: Run generator script
        run: npm run dev-generate-event-docs
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update event documentation
          file_pattern: "*.md"